apiVersion: v1
baseDomain: crt-stage.com
compute:
- hyperthreading: Enabled
  name: worker
  platform:
    aws:
      type: m4.xlarge
      zones:
      - us-east-2a
      - us-east-2b
      - us-east-2c
  replicas: 2
controlPlane:
  hyperthreading: Enabled
  name: master
  platform:
    aws:
      type: m4.large
      zones:
      - us-east-2a
      - us-east-2b
      - us-east-2c
  replicas: 3
metadata:
  creationTimestamp: null
  name: member
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineCIDR: 10.0.0.0/16
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
platform:
  aws:
    region: us-east-2
pullSecret: '${PULL_SECRET}'
sshKey: |
  ${SSH_PUBLIC_KEY}
