---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  labels:
    opsrc-provider: codeready-toolchain
  name: hosted-toolchain-operators
  namespace: ${NAMESPACE}
spec:
  sourceType: grpc
  image: quay.io/codeready-toolchain/hosted-toolchain-index:latest
  displayName: Hosted Toolchain Operators
  updateStrategy:
    registryPoll:
      interval: 5m
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: ${NAME}
  namespace: ${NAMESPACE}
spec:
  targetNamespaces:
    - ${NAMESPACE}
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ${NAME}
  namespace: ${NAMESPACE}
spec:
  channel: staging
  installPlanApproval: Automatic
  name: ${OPERATOR_NAME}
  source: hosted-toolchain-operators
  sourceNamespace: ${NAMESPACE}
---
